version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - '27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  backend:
    build: .
    ports:
      - '9000:9000'
    restart: 'always'
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: admin
      MONGODB_USER: admin
      MONGODB_PWD: admin
      SERVER_PORT: 9000
